Task 4
Reallocman/Go2Epam pull request #4
Opened 2021-07-16 18:23 UTC by Reallocman

2021-07-17 06:27 UTC, rat6666 requested changes

2021-07-17 06:27 UTC, rat6666 commented on Task_4/main.go
> +	// add appropriate methods
meaningless comment

2021-07-17 06:27 UTC, rat6666 commented on Task_4/main.go
> +	// choose your own dimensions
meaningless comment

2021-07-17 06:27 UTC, rat6666 commented on Task_4/main.go
> +}
Why is everything in one file? This was just an example. Please, move interface and entities in different files/packages

2021-07-18 06:31 UTC, rat6666 approved these changes

2021-07-19 11:34 UTC, dimonl approved these changes

2021-07-19 11:34 UTC, dimonl commented on Task_4/shapes/shapes.go
> +
remove empty lines in the end of the file

2021-07-20 12:56 UTC, merged