lesson_5
Reallocman/Go2Epam pull request #5
Opened 2021-07-21 17:15 UTC by Reallocman

2021-07-21 18:25 UTC, dimonl approved these changes
Need to format all your file. It's hard to read. Try to use 'go fmt ./...' in root folder of your project

2021-07-21 19:18 UTC, rat6666 requested changes

2021-07-21 19:18 UTC, rat6666 commented on Task_4/main.go
remove please extra empty line

2021-07-21 19:18 UTC, rat6666 commented on Task_4/shapes/circle.go
> +	if c.Radius<0{
code not formated (missed space)

2021-07-21 19:18 UTC, rat6666 commented on Task_4/shapes/circle.go
> +	if c.Radius<0{
function should return error in case if values invalid

2021-07-21 19:18 UTC, rat6666 commented on Task_4/shapes/circle_test.go
> +
extra empty line

2021-07-21 19:18 UTC, rat6666 commented on Task_4/shapes/circle_test.go
> +
extra empty line

2021-07-21 19:18 UTC, rat6666 commented on Task_4/shapes/rectangle.go
> +	if r.Height<0 || r.Width<0{
function should return error

2021-07-21 19:18 UTC, rat6666 commented on Task_4/shapes/rectangle_test.go
> +
emptyy extra line

2021-07-21 19:18 UTC, rat6666 commented on Task_4/shapes/rectangle_test.go
> +
the same here

2021-07-24 07:17 UTC, rat6666 approved these changes

2021-07-24 11:45 UTC, merged